### ISSUE TITLE
Podcasts showing in search

### ISSUE THREAD

**Issue by francescoaracu** [theRealPadster/spicetify-hide-podcasts#23]
**Describe the bug**
Title is self-explanatory.

**Screenshots**
![image](https://user-images.githubusercontent.com/48188510/146681770-182e5f91-c454-4081-bd72-5024e4eac858.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Spotify version: 1.1.74.631.g0b24d9ad
 - Spicetify version: 2.8.3
 - Extension version: 2.1.0

**Comment by theRealPadster** [comment]
Looks like the class on those cards is broken so it's not finding it. 
`.Em2LrSSfvrgXQoajs6cm` should be `.x-categoryCard-CategoryCard`
I'll see if I can get that added to the Spicetify CSS map...

**Comment by theRealPadster** [comment]
@francescoaracu My PR has been merged in. You can grab the latest CSS map from git by running `spicetify restore backup apply`, and it looks like it works again :) 

Feel free to re-open if this doesn't fully solve the problem.

**Comment by francescoaracu** [comment]
I've just executed the `restore backup apply` command, but...
![image](https://user-images.githubusercontent.com/48188510/146906930-6438376e-49f9-4b61-ad2d-8f288058f91a.png)
It seems that also the search placeholder didn't change (I'm assuming, from the Readme, that your extensions removes "podcasts" from it).

**Comment by theRealPadster** [comment]
Can you open the inspector and check what classes are on that podcast card? It should have this class:
![image](https://user-images.githubusercontent.com/1565883/146937193-4f094ed5-dc94-4ffe-b058-0d4defe3c21e.png)

It also looks like the CSS map is broken for the search input, so that's not being found either. 🤔

**Comment by francescoaracu** [comment]
Podcast card as shown in Inspector
![image](https://user-images.githubusercontent.com/48188510/146944060-bed73d12-0b3c-41ea-a93f-555d9c29beb3.png)

Search input
![image](https://user-images.githubusercontent.com/48188510/146944177-170c8259-fd60-4d63-9790-1f4c7dbaa895.png)

**Comment by francescoaracu** [comment]
UPDATE: on the first usage of Search page, Podcasts are showing; when I change the view (eg. to Home) and then I return to Search, Podcasts are not showing anymore!

Image proof:
![image](https://user-images.githubusercontent.com/48188510/146945504-7f1e0cb3-2609-433d-a3d5-8c66eb913b0f.png)

**Comment by theRealPadster** [comment]
I submitted a PR for the search input, so that the placeholder can be detected. Same deal as before, `spicetify backup restore apply` once it's merged. 

Also, the css mapping was broken for the how it detects when the search page has loaded. I've changed the selector I'm using and it seems to detect it now when I run locally. It's the latest commit on the main branch.

**Comment by theRealPadster** [comment]
Search input PR is merged, and `spicetify backup restore apply` seems to get the search entry placeholder replacement working again. Is there anything that's still not working for you @francescoaracu ?

**Comment by francescoaracu** [comment]
Can confirm it's working, thx a lot for your work!
