### ISSUE TITLE
Does not work ?

### ISSUE THREAD

**Issue by Darkempire78** [theRealPadster/spicetify-hide-podcasts#5]
I downloaded and activated the extension, but posdcasts are visible. 
I already tried to reloead Spotify.
![image](https://user-images.githubusercontent.com/50015928/105228715-33919180-5b63-11eb-9f20-af3d3bd34895.png)

**Comment by Darkempire78** [comment]
But the podcasts button link in the sidebar is hiden but not the podcast carousel items

**Comment by theRealPadster** [comment]
Hmm. The "is it a podcast carousel" check actually just checks for the word "Podcast" in the carousel title or description, which doesn't appear to be in that carousel in your screenshot. I have another idea, it seems to set a class on podcast items, so I'll try targeting carousels via that.

**Comment by theRealPadster** [comment]
@Darkempire78 Alright, would you be able to download the latest version, run `spicetify apply` and try now?

**Comment by Darkempire78** [comment]
I will try this tomorrow

**Comment by Darkempire78** [comment]
Perfect, it's good!

**Comment by theRealPadster** [comment]
@Darkempire78 Would you be able to update your Spotify and check if it's still working? I have noticed mine showing up again after updating Spotify, which I have made an issue of in  #6 

I'm guessing that mine are showing up still because they're technically playlists that have podcast items inside them. I'm just wondering if the method I switched to is still working in your case.

**Comment by Darkempire78** [comment]
I will check this

**Comment by Darkempire78** [comment]
It's working!
